[api]
enabled = true
host = "firelink"
port = 8000
# api_key = "{{ getpw "taskdog/api_key" }}"   # GET FROM ENV INSTEAD

[region]
country = "CA"

[ui]
theme = "tokyo-night"           # good
# theme = "catppuccin-mocha"    # nah
# theme = "kaolin-valley-dark"  # not supported
# theme = "onedark"             # not supported

# textual-dark - Default dark theme
# dracula - Dracula color scheme
# nord - Nord color scheme
# gruvbox - Gruvbox color scheme
