#!/bin/bash
#
#     █████╗ ██╗     ██╗ █████╗  ██████╗███████╗ ██████╗
#    ██╔══██╗██║     ██║██╔══██╗██╔════╝██╔════╝██╔════╝
#    ███████║██║     ██║███████║╚█████╗ █████╗  ╚█████╗
#    ██╔══██║██║     ██║██╔══██║ ╚═══██╗██╔══╝   ╚═══██╗
# ██╗██║  ██║███████╗██║██║  ██║██████╔╝███████╗██████╔╝
# ╚═╝╚═╝  ╚═╝╚══════╝╚═╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚═════╝

# PINNED: Edit this file
alias edit-alias='$(gum choose --header="Choose editor:" micro nano) $HOME/.aliases'
alias alias-edit='edit-alias'
#

# NEW
alias as='as-user'
alias lazylog='sudo lazyjournal -u 2 -t 1000'   # update every 2 seconds, reduce max to 100 lines to make fster

## EDITOR
alias mu=e

# DOCKER
alias d='sudo docker'
alias d-ps='sudo docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"' #\t{{.Image}}"'
alias d-up='sudo docker compose up --remove-orphans'
alias d-down='sudo docker compose down --remove-orphans'
alias d-watch='sudo docker logs -f'


## navigation: cd, ls =================================
export _ZO_DATA_DIR=/data/zoxide 	#Path for zoxide data files
# export _ZO_ECHO=1    				#Print the matched directory before navigating to it when set to 1
# make this one conditional, if zoxide installed
if command -v zoxide; then
	alias cd='z'
fi
alias ..='cd ..'
alias .-='cd -'
alias cdi='cd "$(gum file -a --height=20 --directory)"'
# eza
eza_core="--header --long --icons --group-directories-first --time-style=relative --sort Name --ignore-glob='lost+found'"
eza_git="$eza_core --git --git-repos"
alias l="eza $eza_core"
alias ls='l --smart-group --no-filesize'         # simple view
alias ll="eza $eza_git --group --no-filesize"    # full view
alias lls='ll --total-size'                      # + sizes (slower)
alias ld="eza $eza_git --only-dirs  --all --smart-group --no-filesize"  # dirs only
alias lf="eza $eza_git --only-files --all --smart-group --total-size"   # files only
alias fm="source $HOME/bin/fm"
# navigation ========================================================


## filesystem ops =======================
if command -v bat &> /dev/null; then
    alias cat='bat'
fi
alias compress='tar -czvf'
alias extract='tar -xzvf'
alias tarlist='tar -tzvf'
alias zip='zip -v'
alias cp='cp -vi'
alias mv='mv -vi'
alias rm='rm -vi'
alias mkdir='mkdir -v'
alias rmdir='rmdir -v'
alias chmod='chmod -v'
alias grep='grep --color=auto'
# ======================================


#===============================================================

# Tailscale
alias vpn='sudo tailscale'

# Systemctl
alias sys='sudo systemctl'
alias syslog='sudo journalctl -u'
alias sys-reload='sudo systemctl daemon-reload'



# Python
alias py='uv run'


# gum
export GUM_SPIN_SPINNER="points"
alias gf='gum file -a --height=20'
alias gd='gum file -a --height=20 --directory'


## network manager (nmcli)
alias wifi='nmcli dev wifi'
alias connect='nmcli --ask device wifi connect'
## network manager (nmcli)


## common typos
alias gti='git'
alias sl='ls'
## common typos



###################################################################################################################################

# 
# if [ $(command -v mycli) ]; then
#     alias mysql='mycli -u adi'
# else
#     alias mysql='mysql -u adi -p'
# fi
# 
# if [ $(command -v logo-ls) ]; then
#     alias lls="logo-ls"
#     alias lla="logo-ls -l --all"
# fi
# 
# if [ $(command -v ripgrep) ]; then
#     alias grep="ripgrep"
# fi
# 
# if [ $(command -v go-mtpfs) ]; then
#     alias mount-phone="go-mtpfs $HOME/Phone &>/dev/null & disown"
# fi
# 
# if [ $(command -v fusermount) ]; then
#     alias unmount-phone="fusermount -u $HOME/Phone"
# fi
# 
# if [ $(command -v udisksctl) ]; then
#     alias mount-iso="udisksctl loop-setup -r -f"
#     alias unmount-iso="udisksctl loop-delete -b"
#     alias mount-ssd="udisksctl mount -b /dev/nvme0n1p1"
#     alias unmount-ssd="udisksctl unmount -b /dev/nvme0n1p1"
# fi
# 
# if [ $(command -v ranger) ]; then
#     alias r="ranger"
#     alias fm="ranger"
# fi
# 
# if [ $(command -v broot) ]; then
#     alias br='broot -dhp'
#     alias bs='broot --sizes'
# fi
# 
# if [ $(command -v ptsh) ]; then
#     # alias ls='ptls -la'
#     alias me-in=ptpwd
#     alias mkdir=ptmkdir
#     # alias touch=pttouch
# fi
# 
# if [ $(command -v yt-dlp) ]; then
#     alias yta-aac="yt-dlp --extract-audio --audio-format aac "
#     alias yta-best="yt-dlp --extract-audio --audio-format best "
#     alias yta-flac="yt-dlp --extract-audio --audio-format flac "
#     alias yta-m4a="yt-dlp --extract-audio --audio-format m4a "
#     alias yta-mp3="yt-dlp --extract-audio --audio-format mp3 "
#     alias yta-opus="yt-dlp --extract-audio --audio-format opus "
#     alias yta-vorbis="yt-dlp --extract-audio --audio-format vorbis "
#     alias yta-wav="yt-dlp --extract-audio --audio-format wav "
#     alias ytv-best="yt-dlp -f bestvideo+bestaudio "
# fi
# 
# if [ $(command -v duf) ]; then
#     alias df='duf'
# else
#     alias df='df -h'
# fi
# 
# if [ $(command -v yay) ]; then
#     alias yaconf='yay -Pg'
#     alias yaupg='yay -Syu'
#     alias yas='yay -Syu --noconfirm'
#     alias yain='yay -S'
#     alias yains='yay -U'
#     alias yare='yay -R'
#     alias yarem='yay -Rns'
#     alias yarep='yay -Si'
#     alias yareps='yay -Ss'
#     alias yaloc='yay -Qi'
#     alias yalocs='yay -Qs'
#     alias yalst='yay -Qe'
#     alias yaorph='yay -Qtd'
#     alias yainsd='yay -S --asdeps'
#     alias yamir='yay -Syy'
#     alias yaupd="yay -Sy"
#     alias upgrade='yay -Syu'
# fi
# 
# if [ $(command -v emacs) ]; then
#     alias em="/usr/bin/emacs -nw"
#     alias emacs="emacsclient -c -a 'emacs'"
#     alias doomsync="~/.emacs.d/bin/doom sync"
#     alias doomdoctor="~/.emacs.d/bin/doom doctor"
#     alias doomupgrade="~/.emacs.d/bin/doom upgrade"
# fi

# alias tsm='transmission-cli -D -u 10 -w ~/Downloads/torrents'
# alias zth='zathura'
# alias f="clr && fzf"
# alias music="youtube-viewer"
# alias anime="ani-cli"
# alias flix="notflix"
# alias dmenu='dmenu -i -l 10 -fn "Iosevka Nerd Font" -p "Select File: " -nb "#282a36" -nf "#f8f8f2" -sf "#44475a" -sb "#bd93f9" '
# alias s='startx'
# alias mail="neomutt"
# alias t='bpytop'
# alias tty='tty-clock -C6 -c -t'
# alias weather='clrscr && curl -s wttr.in/gwalior | head -n $(($(curl -s wttr.in/gwalior | wc -l)  - 2)) | tail -n $(($(curl -s wttr.in/gwalior | wc -l)  - 4))'
# alias killl='killall -q'
# alias wal='feh --bg-fill -z'
# alias lock='xscreensaver-command -lock'
# alias tmux="TERM=screen-256color-bce tmux"
# alias cat='bat'
# alias nano='nano -00x'
# alias du='ncdu -x --color off'
# alias ncmpcpp='ncmpcpp ncmpcpp_directory=$HOME/.config/ncmpcpp/'
# alias spotify='spt'
# alias mocp='mocp -M "$XDG_CONFIG_HOME"/moc -O MOCDir="$XDG_CONFIG_HOME"/moc'
# alias tos="~/thinkorswim/thinkorswim"
# alias most='du -hsx * | sort -rh | head -10'
# alias wget="wget -c"
# alias tips='lbrynet txo spend --type=support --is_not_my_input --blocking'
# alias calc='bc -l'
# alias bt='bluetoothctl'
# alias jctl="journalctl -p 3 -xb"
# alias grep='grep --color=auto'
# alias fgrep='fgrep --color=auto'
# alias egrep='egrep --color=auto'
# alias edex='cd ~/.dotfiles/apps && ./edex.AppImage'
# alias retro='cd ~/.dotfiles/apps && ./retro.AppImage'
# 
# alias free='free -m'
# alias psmem='ps auxf | sort -nr -k 4'
# alias psmem10='ps auxf | sort -nr -k 4 | head -10'
# alias pscpu='ps auxf | sort -nr -k 3'
# alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
# alias paux='ps aux | grep'
# 
# alias copy='xsel --clipboard --input'
# alias paste='xsel --clipboard --output'
# alias xclip='xclip -selection clipboard'
# 
# alias tb="nc termbin.com 9999"
# alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"
# 
# alias ddate='date +"%R - %a, %B %d, %Y" | xclip -select clipboard && date +"%R - %a, %B %d, %Y"'
# alias dday='date +"%Y.%m.%d - " | xclip -select clipboard ; date +"%Y.%m.%d"'
# alias week='date +%V'
# alias ping='ping -c 5'
# alias fastping='ping -c 100 -s .2'
# alias rec='gpg --recv-keys --keyserver hkp://pgp.mit.edu'

## Additional Aliases
# alias x='chmod +x'
# alias porn='mpv "http://www.pornhub.com/random"'
# alias ip='curl ipinfo.io/ip'
# alias :q='exit'
# alias please='sudo $(fc -ln -1)'
# alias pip-update='sudo pip3 list --outdated | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U'
# 
# alias npm-update='sudo npm install npm@latest -g'
# 
# # alias todoe='nvim ~/Dropbox/writing/notes/To-do.md'
# alias nvconfig="cd ~/.config/nvim && nvim init.lua"
# alias zedit="nvim ~/zsh/.zshrc"
# alias bedit="nvim ~/.bashrc"
# alias fedit="nvim $XDG_CONFIG_HOME/fish/config.fish"
# alias visudo="nvim /etc/sudoers"
# alias vim="vim -u ~/.config/vim/.vimrc"
# 
# alias reboot="sudo /sbin/reboot"
# alias poweroff="sudo /sbin/poweroff"
# alias halt="sudo /sbin/halt"
# alias shutdown="sudo /sbin/shutdown"
# alias flighton='sudo rfkill block all'
# alias flightoff='sudo rfkill unblock all'
# alias snr='sudo service network-manager restart'
# alias logout="bspc quit"
# alias suspend="systemctl suspend; locklauncher"
# alias cls="clear"
# alias clr="clear"
# alias clrscr='echo -en "\x1b[2J\x1b[1;1H" ; echo; header; echo'
# 
# ## Get fastest mirrors
# alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
# alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
# alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
# alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
# 
# alias kev="xev -event keyboard"
# 
# alias cclock="watch -t -n1 'date +%T | figlet' | lolcat"
# alias tty-clock="tty-clock -S -c -C4 -D -s -n"
# alias ccbonsai="cbonsai -ilt 0.02 -c '  ,  ,  ,  ,  ' -L 5"
# alias fzi="$HOME/.fzfimg.sh"
# alias fzr="fzf --layout=reverse --prompt ' ' --pointer '=>' --preview='less {}' --bind shift-up:preview-page-up,shift-down:preview-page-down"
# 
# alias yt="ytfzf -t"
# alias startx='startx -- -keeptty >~/.xorg.log 2>&1'
# 
# alias ....='cd ../../../'
# alias .....='cd ../../../../'
# alias ......='cd ../../../../../'
# alias .1='cd -1'
# alias .2='cd -2'
# alias .3='cd -3'
# alias .4='cd -4'
# alias .5='cd -5'
# alias .6='cd -6'
# alias .7='cd -7'
# alias .8='cd -8'
# alias .9='cd -9'
# alias _='sudo'
# alias afind='ack -il'
# 
# alias rd='rmdir'
# alias run-help='man'
# 
# alias i="sudo pacman -S"
# alias pacupg='sudo pacman -Syu'
# alias pacin='sudo pacman -S'
# alias pacins='sudo pacman -U'
# alias pacre='sudo pacman -R'
# alias pacrem='sudo pacman -Rns'
# alias pacrep='pacman -Si'
# alias pacreps='pacman -Ss'
# alias pacloc='pacman -Qi'
# alias paclocs='pacman -Qs'
# alias pacinsd='sudo pacman -S --asdeps'
# alias pacmir='sudo pacman -Syy'
# alias paclsorphans='sudo pacman -Qdt'
# alias pacrmorphans='sudo pacman -Rs $(pacman -Qtdq)'
# alias pacfileupg='sudo pacman -Fy'
# alias pacfiles='pacman -F'
# alias pacls='pacman -Ql'
# alias pacown='pacman -Qo'
# alias pacupd="sudo pacman -Sy"
# alias upgrade='npm-update; pip-update; sudo pacman -Syyu'
# alias update='sudo pacman -Syyu'
# alias unlock='sudo rm /var/lib/pacman/db.lck'
# alias cleanup='sudo pacman -Rns (pacman -Qtdq)'
# 
# alias clone='cd $HOME/Downloads/git-repos/ && git clone'
# alias commit="git commit -m"
# alias push="git push origin"
# alias pull="git pull origin"
# 
# alias g=git
# alias ga='git add'
# alias gaa='git add --all'
# alias gam='git am'
# alias gama='git am --abort'
# alias gamc='git am --continue'
# alias gams='git am --skip'
# alias gamscp='git am --show-current-patch'
# alias gap='git apply'
# alias gapa='git add --patch'
# alias gapt='git apply --3way'
# alias gau='git add --update'
# alias gav='git add --verbose'
# alias gb='git branch'
# alias gbD='git branch -D'
# alias gba='git branch -a'
# alias gbd='git branch -d'
# alias gbda='git branch --no-color --merged | command grep -vE "^([+*]|\s*($(git_main_branch)|$(git_develop_branch))\s*$)" | command xargs git branch -d 2>/dev/null'
# alias gbl='git blame -b -w'
# alias gbnm='git branch --no-merged'
# alias gbr='git branch --remote'
# alias gbs='git bisect'
# alias gbsb='git bisect bad'
# alias gbsg='git bisect good'
# alias gbsr='git bisect reset'
# alias gbss='git bisect start'
# alias gc='git commit -v'
# alias 'gc!'='git commit -v --amend'
# alias gca='git commit -v -a'
# alias 'gca!'='git commit -v -a --amend'
# alias gcam='git commit -a -m'
# alias 'gcan!'='git commit -v -a --no-edit --amend'
# alias 'gcans!'='git commit -v -a -s --no-edit --amend'
# alias gcas='git commit -a -s'
# alias gcasm='git commit -a -s -m'
# alias gcb='git checkout -b'
# alias gcd='git checkout $(git_develop_branch)'
# alias gcf='git config --list'
# alias gclr='git clone --recurse-submodules'
# alias gcl='git clone --quiet'
# alias gcld='git clone --depth'
# alias gclean='git clean -id'
# alias gcm='git checkout $(git_main_branch)'
# alias gcmsg='git commit -m'
# alias 'gcn!'='git commit -v --no-edit --amend'
# alias gco='git checkout'
# alias gcor='git checkout --recurse-submodules'
# alias gcount='git shortlog -sn'
# alias gcp='git cherry-pick'
# alias gcpa='git cherry-pick --abort'
# alias gcpc='git cherry-pick --continue'
# alias gcs='git commit -S'
# alias gcsm='git commit -s -m'
# alias gcss='git commit -S -s'
# alias gcssm='git commit -S -s -m'
# alias gd='git diff'
# alias gdca='git diff --cached'
# alias gdct='git describe --tags $(git rev-list --tags --max-count=1)'
# alias gdcw='git diff --cached --word-diff'
# alias gds='git diff --staged'
# alias gdt='git diff-tree --no-commit-id --name-only -r'
# alias gdup='git diff @{upstream}'
# alias gdw='git diff --word-diff'
# alias gf='git fetch'
# alias gfa='git fetch --all --prune --jobs=10'
# alias gfg='git ls-files | grep'
# alias gfo='git fetch origin'
# alias gg='git gui citool'
# alias gga='git gui citool --amend'
# alias ggpull='git pull origin "$(git_current_branch)"'
# alias ggpur=ggu
# alias ggpush='git push origin "$(git_current_branch)"'
# alias ggsup='git branch --set-upstream-to=origin/$(git_current_branch)'
# alias ghh='git help'
# alias gignore='git update-index --assume-unchanged'
# alias gignored='git ls-files -v | grep "^[[:lower:]]"'
# alias git-svn-dcommit-push='git svn dcommit && git push github $(git_main_branch):svntrunk'
# alias gk='\gitk --all --branches &!'
# alias gke='\gitk --all $(git log -g --pretty=%h) &!'
# alias gl='git pull'
# alias glg='git log --stat'
# alias glgg='git log --graph'
# alias glgga='git log --graph --decorate --all'
# alias glgm='git log --graph --max-count=10'
# alias glgp='git log --stat -p'
# alias glo='git log --oneline --decorate'
# alias globurl='noglob urlglobber '
# alias glod='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'\'
# alias glods='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'\'' --date=short'
# alias glog='git log --oneline --decorate --graph'
# alias gloga='git log --oneline --decorate --graph --all'
# alias glol='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'
# alias glola='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'' --all'
# alias glols='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'' --stat'
# alias glp=_git_log_prettily
# alias glum='git pull upstream $(git_main_branch)'
# alias gm='git merge'
# alias gma='git merge --abort'
# alias gmom='git merge origin/$(git_main_branch)'
# alias gmtl='git mergetool --no-prompt'
# alias gmtlvim='git mergetool --no-prompt --tool=vimdiff'
# alias gmum='git merge upstream/$(git_main_branch)'
# alias gp='git push'
# alias gpd='git push --dry-run'
# alias gpf='git push --force-with-lease'
# alias 'gpf!'='git push --force'
# alias gpoat='git push origin --all && git push origin --tags'
# alias gpr='git pull --rebase'
# alias gpristine='git reset --hard && git clean -dffx'
# alias gpsup='git push --set-upstream origin $(git_current_branch)'
# alias gpu='git push upstream'
# alias gpv='git push -v'
# alias gr='git remote'
# alias gra='git remote add'
# alias grb='git rebase'
# alias grwh='git rm --cached `git ls-files -i -c --exclude-from=.gitignore`'
# alias grwhx='git ls-files -i -c --exclude-from=.gitignore | xargs git rm --cached'
# alias grad='git rm -r --cached . && git add .'
# alias grba='git rebase --abort'
# alias grbc='git rebase --continue'
# alias grbd='git rebase $(git_develop_branch)'
# alias grbi='git rebase -i'
# alias grbm='git rebase $(git_main_branch)'
# alias grbo='git rebase --onto'
# alias grbom='git rebase origin/$(git_main_branch)'
# alias grbs='git rebase --skip'
# alias grep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
# alias grev='git revert'
# alias grh='git reset'
# alias grhh='git reset --hard'
# alias grm='git rm'
# alias grmc='git rm --cached'
# alias grmv='git remote rename'
# alias groh='git reset origin/$(git_current_branch) --hard'
# alias grrm='git remote remove'
# alias grs='git restore'
# alias grset='git remote set-url'
# alias grss='git restore --source'
# alias grst='git restore --staged'
# alias grt='cd "$(git rev-parse --show-toplevel || echo .)"'
# alias gru='git reset --'
# alias grup='git remote update'
# alias grv='git remote -v'
# alias gsb='git status -sb'
# alias gsd='git svn dcommit'
# alias gsh='git show'
# alias gsi='git submodule init'
# alias gsps='git show --pretty=short --show-signature'
# alias gsr='git svn rebase'
# alias gss='git status -s'
# alias gst='git status'
# alias gsta='git stash push'
# alias gstaa='git stash apply'
# alias gstall='git stash --all'
# alias gstc='git stash clear'
# alias gstd='git stash drop'
# alias gstl='git stash list'
# alias gstp='git stash pop'
# alias gsts='git stash show --text'
# alias gstu='gsta --include-untracked'
# alias gsu='git submodule update'
# alias gsw='git switch'
# alias gswc='git switch -c'
# alias gswd='git switch $(git_develop_branch)'
# alias gswm='git switch $(git_main_branch)'
# alias gtl='gtl(){ git tag --sort=-v:refname -n -l "${1}*" }; noglob gtl'
# alias gts='git tag -s'
# alias gtv='git tag | sort -V'
# alias gunignore='git update-index --no-assume-unchanged'
# alias gunwip='git log -n 1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'
# alias gup='git pull --rebase'
# alias gupa='git pull --rebase --autostash'
# alias gupav='git pull --rebase --autostash -v'
# alias gupv='git pull --rebase -v'
# alias gwch='git whatchanged -p --abbrev-commit --pretty=medium'
# alias gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign -m "--wip-- [skip ci]"'
# 
# alias ldot='ls -ld .*'
# alias lS='ls -1FSsh'
# alias lart='ls -1Fcart'
# alias lrt='ls -1Fcrt'
# 
# alias grepin='grep -i'
# alias sgrep='grep -R -n -H -C 5 --exclude-dir={.git,.svn,CVS} '
# 
# alias t='tail -f'
# alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"
# alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"
# alias tofish="sudo chsh $USER -s /bin/fish && echo 'Now log out.'"
# 
# # Command line shortcuts
# alias -g H='| head'
# alias -g T='| tail'
# alias -g G='| grep'
# alias -g S='| sed'
# alias -g L="| less"
# alias -g M="| most"
# alias -g LL="2>&1 | less"
# alias -g CA="2>&1 | bat -A"
# alias -g NE="2> /dev/null"
# alias -g NUL="> /dev/null 2>&1"
# alias -g P="2>&1| pygmentize -l pytb"
# 
# alias dud='du -d 1 -h'
# alias ff='find . -type f -name'
# 
# alias h='history'
# alias hgrep="fc -El 0 | grep"
# alias help='man'
# alias p='ps -f'
# alias sorter='sort -n -r'
# alias unexport='unset'
# 
# alias cp="rsync -WavP --human-readable --progress"
# alias mv='mv -i'
# # alias rm="trash --trash-dir='$HOME/.Trash' --recursive"
# 
# alias -s pdf=zathura
# alias -s ps=gv
# alias -s dvi=xdvi
# alias -s chm=xchm
# alias -s djvu=djview
# 
# alias -s zip="unzip -l"
# alias -s rar="unrar l"
# alias -s tar="tar tf"
# alias -s tar.gz="echo "
# alias -s ace="unace l"
# 
# # Tmux Aliases
# alias attach='tmux attach -t'
# alias ts="tmux ls"
# 
# # sudo not required for some system commands
# for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
# 	alias $command="sudo $command"
# done; unset command
