#!/bin/bash

CONFIG=$HOME/cfg

run() {
	case "$1" in
		help) show_usage ;;
		'') apply_all_settings ;;
		*)  apply_one "$1" ;;
	esac
}

show_usage() {
	echo "~/cfg/apply OR ~/cfg/apply \"git\""
}

apply_one() {
	dir="$CONFIG/$1"
	if [[ ! -d "$dir" ]]; then
		echo "$dir does not exist"
		exit 1
	fi
	"$dir/apply.sh"
}

apply_all_settings() {
	echo "for each dir run dir/apply.sh"
}

run "$@"
