#!/bin/bash

set -eu

ECHO "ENSURE CONNECTION WITH $HOST: ping"

git -C ~/env push
gopass sync
gpg --export-secret-keys --armor > ~/gopass.key
rsync ~/gopass.key $HOST:~/gopass.key
rm ~/gopass.key

echo "GOPASS KEY HAS BEEN TRANSFERRED TO $HOST:~/gopass.key"
