#!/usr/bin/env bash
set -euo pipefail

# ETC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export BIN="$ROOT/.bin"		# contains dependencies
export DSL="$ROOT/.dsl"		# contains language definitions
export GUM_SPIN_SPINNER=meter
export GUM_SPIN_ALIGN=left
export GUM_SPIN_TIMEOUT=300s
export GUM_SPIN_SHOW_ERROR=true
# GUM_SPIN_SHOW_OUTPUT=true
export gum=$BIN/gum

for dsl in "$DSL"/*.sh; do
    source "$dsl"
done

##############################################################

# HOSTS IDENTIFICATION ************************************

host firelink at 100.121.116.55
	is  headless server 	
	os 	Debian
:

host majula at 100.109.130.76 
	is	headless server	
	os	Debian
:

host xenon
	is	gaming pc
	os 	PopOS		# change to PikaOS
	de	COSMIC  # to be changed to Niri
:

host luminous at 100.74.47.77
	is gaming pc
	os PikaOS
	de Niri
:

host aran
	is 	low-powered pc
	os	Debian
	# de	KDE? not sure. Try LxQT or IceWM or just fucking sell it
:

# NAMESPACE ***************************************
# 	- be located at the root of the filesystem
# 	- be owned by $USER by default
# 	- be honored in its purpose, services and utitlies shall expect it
# 	- follow my HOST IDENTITY FILESYSTEM standard
namespace data  # Mutable state
namespace repo  # Shared file repository
namespace exe 	# Non-system executables
namespace log   # Non-system log aggregation
namespace net   links to ~/host/net # Network topology
namespace svc   links to ~/host/svc # Services
namespace job   links to ~/host/job # Recurring jobs


echo "PREMATURE EXIT"
exit 1 #*****************************************************

# SERVICES ****************************************
host wiki	# WITHOUT ARGS MEANS LOCALHOST, EVERY DEVICE HAS SILVERBULLET INSTANCE
host nats					at majula
host file-server	at majula
host pocketbase		at majula
host uptime-kuma	at majula
# *************************************************

# IMPORTS *********************************
sync ~/etc					from 'axjab/dotfiles'
set -x
sync /exe					  from 'axjab/executables'
sync /data/secrets	from 'axjab/secrets'
set +x
sync /data/helix		with 'ssh://majula//data/helix'
set +e
sync ~/host  # move to .host?
set -e

# EXPERIMENTAL

# for majula
# 	install this
# 	link that
# 	etc

# *********************

# ENVIRONMENT
install exe-path in sudoers <<-EOF
	Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/exe"
EOF
echo "checkpoint"
exit 0
process	 shell/env 		 to ~/.env
symlink	 shell/aliases to ~/.aliases
symlink	 shell/bashrc  to ~/.bashrc

## FILESYSTEM MOUNTPOINTS
# NEED TAGGING DSL
set +e
mount nfs majula:/mnt/ssd 			onto /mnt/majula.ssd		# for all but Majula
mount dir /mnt/majula.ssd/files onto /repo							# for all but Majula
mount dir /mnt/ssd/data/garage	onto /data/garage/data	# for host majula only
set -e

## APPLICATIONS
set +e
link		niri/config.kdl			to ~/.config/niri/config.kdl
symlink niri/config.kdl			to ~/.config/niri/config.kdl
set -e
# process ssh/config				to ~/.ssh/config
symlink helix/config.toml		to ~/.config/helix/config.toml
symlink helix/lang.toml			to ~/.config/helix/languages.toml
symlink ~/.config/helix 		to /root/.config/helix
# sudo ln -sv ~/.config/helix /root/.config/helix
process aichat/config.yaml 	to ~/.config/aichat/config.yaml    # if u can get secret for ~/.env, a symlink would suffice
symlink bat/config					to /etc/bat/config
symlink gh/config.yml				to ~/.config/gh/config.yml
symlink git/config					to /etc/gitconfig
symlink gopass/config				to ~/.config/gopass/config
symlink sqlite/config				to ~/.sqliterc
symlink starship/config			to ~/.config/starship.toml
symlink taskdog/cli.toml    to ~/.config/taskdog/cli.toml
symlink xdg/dirs 						to ~/.config/user-dirs.dirs
# symlink xdg/locale			to ~/.config/locale.conf  # verify; may be /etc/locale.conf

# reload needed
# 1. load language
# 2. deploy config
# 3. reload parent shell, is it possible?
