#!/usr/bin/env bash
set -euo pipefail

# ETC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export BIN="$ROOT/.bin"		# contains dependencies
export DSL="$ROOT/.dsl"		# contains language definitions
export GUM_SPIN_SPINNER=meter
export GUM_SPIN_ALIGN=left
export GUM_SPIN_TIMEOUT=300s
export GUM_SPIN_SHOW_ERROR=true
# GUM_SPIN_SHOW_OUTPUT=true
export gum=$BIN/gum

# TODO: INCLUDE SELF-SYNC HERE INSTEAD OF sync ~/etc
# TODO: MAJOR WORK: Make this Hostfile orderless, parse everything THEN execute. Perhaps bash is not suited for this?
# TODO: Do tasks in parallel
# sync -> resolve conflicts -> rerun

for dsl in "$DSL"/*.sh; do
    source "$dsl"
done

##############################################################

# PREREQUISITES *****************************************

require internet
require tailnet
require ssh
require github
require repository # NOT IMPLEMENTED; OUT OF SCOPE

namespace data  # Mutable state
namespace repo  # Shared file repository
namespace exe   # Non-system executables
namespace log   # Non-system log aggregation
namespace net   # Network topology
namespace svc   # Services
namespace job   # Recurring jobs

sync ~/etc 					from 'github:axjab/dotfiles'    # self-update
sync /exe 					from 'github:axjab/executables'
sync /data/secrets	from 'github:axjab/secrets'

install exe-path in sudoers <<-EOF
	Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/exe"
EOF

# IDENTITIY ******************************************
exit 1
host firelink at 100.121.116.55
	is  headless server 	
	os 	Debian
:
host majula at 100.109.130.76 
	is	headless server	
	os	Debian
:
host xenon
	is	gaming pc
	os 	PikaOS
	de	Niri
:
host luminous at 100.74.47.77
	is gaming pc
	os PikaOS
	de Niri
:
host aran
	is 	low-powered pc
	os	Debian
:

# SERVICES ****************************************

host service wiki 				at localhost
host service nats					at majula
host service repository		at majula
host service pocketbase		at majula
host service uptime-kuma	at majula

# CONFIGURATION ***********************************
link gopass/config	to ~/.config/gopass/config
process	 shell/env 	to ~/.env
link shell/aliases	to ~/.aliases
link shell/bashrc  	to ~/.bashrc
sync /data/helix		with 'ssh://majula//data/helix'
sync ~/host  # move to .host?

echo "PREMATURE EXIT"
exit 1 #*****************************************************

## FILESYSTEM MOUNTPOINTS
# NEED TAGGING DSL
set +e
mount nfs majula:/mnt/ssd 			onto /mnt/majula.ssd		# for all but Majula
mount dir /mnt/majula.ssd/files onto /repo							# for all but Majula
mount dir /mnt/ssd/data/garage	onto /data/garage/data	# for host majula only
set -e

## APP CONFIG
link		niri/config.kdl			to ~/.config/niri/config.kdl
# process ssh/config				to ~/.ssh/config
symlink helix/config.toml		to ~/.config/helix/config.toml
symlink helix/lang.toml			to ~/.config/helix/languages.toml
symlink ~/.config/helix 		to /root/.config/helix
# sudo ln -sv ~/.config/helix /root/.config/helix
process aichat/config.yaml 	to ~/.config/aichat/config.yaml    # if u can get secret for ~/.env, a symlink would suffice
symlink bat/config					to /etc/bat/config
symlink gh/config.yml				to ~/.config/gh/config.yml
symlink git/config					to /etc/gitconfig
symlink sqlite/config				to ~/.sqliterc
symlink starship/config			to ~/.config/starship.toml
symlink taskdog/cli.toml    to ~/.config/taskdog/cli.toml
symlink xdg/dirs 						to ~/.config/user-dirs.dirs
# symlink xdg/locale			to ~/.config/locale.conf  # verify; may be /etc/locale.conf

# reload needed
# 1. load language
# 2. deploy config
# 3. reload parent shell, is it possible?

# POST-SCRIPTUM NOTES
#
# Namespaces should:
#   - be located at the root of the filesystem
# 	- be owned by $USER by default
# 	- be honored in its purpose by utilities and services
# 	- be mirroring my HOST IDENTITY FILESYSTEM standard

# bootstrap_ssh() {

# 	host <hostname>
# 	  is   <tags...>
# 	  at   <ip or domain.com>
# 	  os   ...
# 	  user <user>

# 	should generate

# 	Host <hostname>
# 	  Hostname <ip or domain.com>
# 	  User <user>


# 	- [ ] update host:~/.ssh/authorized_keys
# 	- [ ] reset remote hosts's sshd_config


# 	ssh exec: add "~/.ssh/*.pub" to "host:~/.ssh/authorized_keys" idempotently

	
# }
