#!/usr/bin/env bash
set -euo pipefail

# TODO: MOVE THIS PREAMBLE ELSEWHERE, THEN INTRODUCE RELOAD CONFIG

ETC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN="$ROOT/.bin"		# contains dependencies
DSL="$ROOT/.dsl"		# contains language definitions

export GUM_SPIN_SPINNER=meter
export GUM_SPIN_ALIGN=left
export GUM_SPIN_TIMEOUT=300s
# export GUM_SPIN_PADDING="1 0"
# GUM_SPIN_SHOW_OUTPUT=true
export GUM_SPIN_SHOW_ERROR=true

for dsl in "$DSL"/*.sh; do
    source "$dsl"
done

##############################################################

# HOST IDENTITY FILESYSTEM
#  https://chatgpt.com/s/t_6a6dcd921f788191b90ef1b6395ab86e

# A NAMESPACE IS LIKE A DECLARATION OF DEPENDENCY
# THE GIVEN DIRECTORIES WILL TAKE ON A SPECIFIC
# ROLE AND THEIR EXISTENCE MUST BE GUARANTEED
# IN ORDER FOR DEPENDENT SERVICES TO USE THEM.
# WITHOUT THESE DIRECTORIES, FAILURES WILL HAPPEN.

# TODO: OWNED BY ME BY DEFAULT
# TODO: THE FOLLOWING NAMESPACES MUST HAVE A CLEAR ROLE INCLUDED WITH THEM
# IF DIRECTORY DOES NOT EXIST, FLAG AS ERROR BUT CARRY ON
namespace data  # Mutable state
namespace repo  # Shared file repository
namespace exe 	# Non-system executables
namespace log   # Non-system log aggregation
namespace net   links to ~/host/net # Network topology
namespace svc   links to ~/host/svc # Services provided by this host
namespace job   links to ~/host/job # Recurring jobs

# WIP: what are the GREAT namespaces of a universal file server?
# As for /fs or /repo:
# /act: active work (workspace)
# /archive: cold storage
# /dump: inbox or unsorted:
# /srv: anything served (assets, html, data, etc.)
# /wiki: knowledge base

# TODO: PROCESS MUST ALWAYS CLEAN UP IF NO CHANGES SINCE LAST BACKUP

# ENVIRONMENT
install exe-path in sudoers <<-EOF
	Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/exe"
EOF
pull 'github.com/axjab/dotfiles'		to ~/env    # bad, instead, detect changes to self and report to user
pull 'github.com/axjab/executables' to /exe
pull 'github.com/axjab/secrets'			to /data/secrets

## SHELL
process	 shell/env 		 to ~/.env
symlink	 shell/aliases to ~/.aliases
symlink	 shell/bashrc  to ~/.bashrc

## FILESYSTEM
mount nfs majula:/mnt/ssd 			onto /mnt/majula.ssd
mount dir /mnt/majula.ssd/files onto /repo

## APPLICATIONS
# process ssh/config				to ~/.ssh/config
symlink helix/config.toml		to ~/.config/helix/config.toml
symlink helix/config.toml		to /root/.config/helix/config.toml
symlink helix/lang.toml			to ~/.config/helix/languages.toml	# bad! missing runtime, need refactor symlink to hanlde absolute and relative paths
symlink helix/lang.toml			to /root/.config/helix/languages.toml  # bad!
process aichat/config.yaml 	to ~/.config/aichat/config.yaml
symlink gh/config.yml				to ~/.config/gh/config.yml
symlink git/config					to /etc/gitconfig
symlink gopass/config				to ~/.config/gopass/config
symlink sqlite/config				to ~/.sqliterc
symlink starship/config			to ~/.config/starship.toml
process taskdog/cli.toml    to ~/.config/taskdog/cli.toml
symlink xdg/dirs 						to ~/.config/user-dirs.dirs
# symlink xdg/locale			to ~/.config/locale.conf  # verify; may be /etc/locale.conf

# reload needed
# 1. load language
# 2. deploy config
# 3. reload parent shell, is it possible?
