# ~/.config/starship.toml

# REFERENCE: https://starship.rs/config
# TODO:
# - Report connection errors: Internet, Tailscale, NATS, LoRa, etc.

"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
scan_timeout = 30
command_timeout = 500
palette = 'foo'
follow_symlinks = true
right_format = "$time"
format = """
(\
  ($jobs )($memory_usage )($cmd_duration )\
  ($netns )($nats )($custom )\
  ($git_status )($git_commit )($git_state )($git_metrics )\
  (\
    $direnv$python$golang$nodejs$rust$env_var\
    $container$docker_container\
  )\
  \n\
)\
$battery\
($username(@$hostname):)$directory$git_branch \
$shlvl$character
"""
# NOTE: $fill has been intentionally omitted because it
# causes ( $fill $emptyvar ) to ALWAYS render (as space)
# when it's the opposite of the desired effect
# logical context and device metrics
# brackets () control adjacent spacing based on existance

# ======================================================

# LOWER RIGHT
# ===========================
[time]
disabled = false
format = '[$time](bold green)' #
time_format = '%T'

# LOWER LEFT
# ===========================
[battery]
disabled = false
format = '[$symbol$percentage$battery]($style) '
full_symbol = '󰁹 '
charging_symbol = '󱐋' # ⚡️  󱐋 󰂄
unknown_symbol = '?'
empty_symbol = '☠'
[username]
style_user = 'dimmed green'
style_root = 'bold green'
format = '[$user]($style)'
[hostname]
ssh_only = true
format = '[$hostname](green)'
ssh_symbol = '🌐'
[directory]
disabled = false
format = '[$path]($style)[$read_only]($read_only_style)'
truncation_length = 4
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'
[git_branch]
disabled = false
format = '[$symbol$branch(:$remote_branch)]($style)'
style = 'purple'
symbol = ''
[shlvl]
disabled = false
format = '[$symbol]($style)'
repeat = true
symbol = '>'
repeat_offset = 1
threshold = 0
[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

# UPPER RIGHT
# =============================
[fill]
symbol = ' '
style = 'dimmed white'
[direnv]
disabled = false

# UPPER LEFT
# ==============================
[jobs]
symbol = '⚙'
format = '[$symbol$number]($style)'
number_threshold = 1
[memory_usage]
disabled = false
threshold = 70
symbol = '⚠RAM'
format = '[$symbol $ram/$ram_total($ram_pct)]($style)'
style = 'bold #ff9f1c'
[nats]
disabled = false
[custom.nats]
disabled = false
description = "Inbound NATS message indicator. Topics: whatsapp, email, ntfy, system, etc."
when = '(( ${nats_msg:-0} > 0 ))'
command = 'echo "$nats_msg"'
symbol = '◈'
format = '[$symbol$output](bold green)'
[git_status]
style = "bold yellow"
format = '([\[$all_status$ahead_behind\]]($style))'
modified = "✎"
staged = "[+](bold green)"
untracked = "[?](bold red)"
deleted = "[×](bold red)"
conflicted = "[⚔](bold red)"
ahead = "[⇡${count}](bold cyan)"
behind = "[⇣${count}](bold magenta)"
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](bold red)"
[git_metrics]
disabled = false
[git_state]
disabled = false
[git_commit]
disabled = false
[cmd_duration]
disabled = false
min_time = 2000
format = '⏳[$duration]($style)'	# The format for the module.
style = 'yellow'
show_milliseconds = true # Shortest duration to show time for (in milliseconds).
show_notifications = true	# Show desktop notifications when command completes.
min_time_to_notify = 60000	# Shortest duration for notification (in milliseconds).
# notification_timeout		# Duration to show notification for (in milliseconds). If unset, notification timeout will be determined by daemon. Not all notification daemons honor this option.

# WIP ====================

# CUSTOM SCRIPTS: https://github.com/starship/starship/discussions/1252?sort=top
# IDEA: TIMER, POMODORO, NEXT DEADLINE (calnedar integration)

[custom.status]
disabled = true
when = true #'[[ "$STARSHIP_CMD_STATUS" != "0" ]]'
command = 'subscript $STARSHIP_CMD_STATUS'
symbol = ''
format = '[$output]($style) '
style = 'red'

[status]
disabled = false
map_symbol = true
recognize_signal_code = true
format = '$symbol[${status}(/${signal_name})]($style)$symbol'
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
# style = 'bg:blue'
symbol = ''
sigint_symbol = '⚡'
# not_found_symbol sigint_symbol signal_symbol 
# not_executable_symbol

# BATTERY DETAILS ***********************************
[[battery.display]] # < 10%
threshold = 10
discharging_symbol = '☠'
style = 'bold red'

[[battery.display]] # < 20%
threshold = 19
discharging_symbol = '󰁺'
style = 'bold red'

[[battery.display]] # < 30%
threshold = 29
discharging_symbol = '󰁻'
style = 'bold yellow'

[[battery.display]] # < 40%
threshold = 39
discharging_symbol = '󰁼'
style = 'bold yellow'

[[battery.display]] # < 50%
threshold = 49
discharging_symbol = '󰁽'
style = 'dimmed yellow'

[[battery.display]] # < 60%
threshold = 59
discharging_symbol = '󰁾'
style = 'dimmed yellow'

[[battery.display]] # < 70%
threshold = 69
discharging_symbol = '󰁿'
style = 'dimmed yellow'

[[battery.display]] # < 80%
threshold = 79
discharging_symbol = '󰂀'
style = 'dimmed green'

[[battery.display]] # < 90%
threshold = 89
discharging_symbol = '󰂁'
style = 'dimmed green'

[[battery.display]] # < 100%
threshold = 95
discharging_symbol = '󱈏'
style = 'fg:#C37093'
#**********************************************8

# [palettes]
[palettes.foo]
# blue = '21'  # will overwrite
mustard = '#af8700'
bright_pink = 'bg:#D1005B fg:#23000F'
pink_bright_text = 'bg:#68032F fg:#F7BCD6'
pink_faded_text = 'bg:#68032F fg:#D7748C'
dark_pink = 'bg:#43001D fg:#C37093'
dark_pink_highlight = 'bg:#43001D fg:#D1005B'
