# ~/.config/starship.toml

# REFERENCE: https://starship.rs/config

"$schema" = 'https://starship.rs/config-schema.json'

# TODO:
# 1. Indicate ACTIVE SSH session
# 2. Report connection errors: Internet, Tailscale, NATS, LoRa, etc.
# 3. [in progress] NOTIFICATION COUNTER; new ntfy messages, new NATS messages, etc.
# 4. 

add_newline = false
scan_timeout = 30
command_timeout = 500
# palette = 'foo'  # defined last
# follow_symlinks

# logical context and device metrics
format = """
$cmd_duration\
$git_branch$git_commit$git_state\
$git_metrics\
$git_status\
$battery\
$jobs\
$sudo\
(\n${custom.messages})
$directory\
$shlvl\
$status\
$character
"""

# session and physical context, answers who? where? when?
right_format = "$username@$hostname$time"

# pinned

[time]
disabled = false
format = '[$time]($style)'
style = 'bold green'
time_format = '%T'

[username]
show_always = true
style_user = 'dimmed white'
style_root = 'white bold'
format = '[$user]($style)'

[hostname]
ssh_only = false
format = '[$hostname]($style) $ssh_symbol'
style = 'dimmed gray'
ssh_symbol = '[\[SSH ACTIVE\] ](bold blue)'  # failed to get symbol in other part of prompt

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

# ---------------------

# pointless ?
[nats]
disabled = false
# name = 'notifications'  # nats context ls
format = '[$symbol]($style)'
style = 'bold purple'

# CUSTOM SCRIPTS: https://github.com/starship/starship/discussions/1252?sort=top
# IDEA: TIMER, POMODORO, NEXT DEADLINE (calnedar integration)
  [custom.messages]
  disabled = false
  description = "Inbound NATS message indicator. Topics: whatsapp, email, ntfy, system, etc."
  when = '(( ${nats_msg:-0} > 0 ))'
  command = 'echo "$nats_msg"'
  symbol = '◈'
  format = '[$symbol$output](bold green)'
  # warning: ⚠

  # [custom.live-clock-icon]
  # command = 'echo "" | cut -c $(($(date +%H)%12+1))'
  # description = "Live updating clock icon, changes hourly. Icons can be customized to your liking."
  # when = true
  # style = "fg:bright-blue bg:black"
  # format = "[$output ]($style)"

  # [custom.files]
  # description = "Show files count for current directory"
  # command = "find ./ -maxdepth 1 -type f | wc -l"
  # format = "📄[$output]($style) "
  # style = "white"
  # when = "true"

  # [custom.directories]
  # description = "Show directory count count for current directory"
  # command = "find ./ -maxdepth 1 -type d | tail -n +2 | wc -l"
  # format = "📁[$output]($style)"
  # style = "blue"
  # when = "true"

# [custom.foo]
# command = 'echo foo' # shows output of command
# detect_files = ['foo'] # can specify filters but wildcards are not supported
# when = ''' test "$HOME" = "$PWD" '''
# format = ' transcending [$output]($style)'

# [custom.time]
# command = 'time /T'
# detect_extensions = ['pst'] # filters *.pst files
# shell = ['pwsh.exe', '-NoProfile', '-Command', '-']

# [custom.time-as-arg]
# command = 'time /T'
# detect_extensions = ['pst'] # filters *.pst files
# shell = ['pwsh.exe', '-NoProfile', '-Command']
# use_stdin = false

[sudo]
disabled = false
format = '[$symbol]($style)'
style = 'bold green'
symbol = '#'

[status]
disabled = false
map_symbol = true
recognize_signal_code = true
format = '$symbol[${status}(/${signal_name})]($style)$symbol'
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
# style = 'bg:blue'
symbol = ''
sigint_symbol = '⚡'
# not_found_symbol sigint_symbol signal_symbol 
# not_executable_symbol

[shell]
disabled = false

[shlvl]
disabled = false
format = '[$symbol]($style)'
repeat = true
symbol = '>'
repeat_offset = 1
threshold = 0

[os]
disabled = false
format = "[($symbol$name)]($style)"
# style = "bold blue"

[memory_usage]
disabled = true
threshold = -1
format = 'via $symbol [${ram}\(${ram_pct}\)( | ${swap})]($style) '
symbol = 'RAM'
style = 'bold dimmed green'

[line_break]
disabled = false

[jobs]
disabled = false
format = '[<](bold green)[$symbol$number jobs]($style) | '
symbol = '+'
symbol_threshold = 1
number_threshold = 2

[localip]
disabled = false
ssh_only = false
format = '[\[$localipv4\]]($style) '
style = 'dimmed yellow'

[git_status]
disabled = false
conflicted = '🏳'
ahead = '🏎💨'
behind = '😰'
diverged = '😵'
up_to_date = '✓'
untracked = '🤷'
stashed = '📦'
modified = '📝'
staged = '[++\($count\)](green)'
renamed = '👅'
deleted = '🗑'

[git_metrics]
disabled = false

[git_state]
disabled = false

[git_commit]
disabled = false
# commit_hash_length = 4
tag_symbol = '🔖 '

[git_branch]
disabled = false

[fill]
disabled = false
symbol = ' '
style = 'dimmed white'

[env_var.SHIT]
disabled = true
format = "with [$env_value]($style) "
default = ''

[directory]
disabled = false
format = '[$path]($style)[$read_only]($read_only_style) '
truncation_length = 3
# truncate_to_repo
# repo_root_style
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'

[cmd_duration]
disabled = true
format = '⏳[$duration]($style)'	# The format for the module.
style = 'yellow'
min_time = 0
show_milliseconds = true # Shortest duration to show time for (in milliseconds).
show_notifications = true	# Show desktop notifications when command completes.
min_time_to_notify = 60000	# Shortest duration for notification (in milliseconds).
# notification_timeout		# Duration to show notification for (in milliseconds). If unset, notification timeout will be determined by daemon. Not all notification daemons honor this option.

[battery]
disabled = false
format = '[$symbol$percentage$battery]($style) '
full_symbol = '󰁹 '
charging_symbol = '󱐋' # ⚡️  󱐋 󰂄
unknown_symbol = '?'
empty_symbol = '☠'

  [[battery.display]] # < 10%
  threshold = 10
  discharging_symbol = '☠'
  style = 'bold red'

  [[battery.display]] # < 20%
  threshold = 19
  discharging_symbol = '󰁺'
  style = 'bold red'

  [[battery.display]] # < 30%
  threshold = 29
  discharging_symbol = '󰁻'
  style = 'bold yellow'

  [[battery.display]] # < 40%
  threshold = 39
  discharging_symbol = '󰁼'
  style = 'bold yellow'

  [[battery.display]] # < 50%
  threshold = 49
  discharging_symbol = '󰁽'
  style = 'dimmed yellow'

  [[battery.display]] # < 60%
  threshold = 59
  discharging_symbol = '󰁾'
  style = 'dimmed yellow'

  [[battery.display]] # < 70%
  threshold = 69
  discharging_symbol = '󰁿'
  style = 'dimmed yellow'

  [[battery.display]] # < 80%
  threshold = 79
  discharging_symbol = '󰂀'
  style = 'dimmed green'

  [[battery.display]] # < 90%
  threshold = 89
  discharging_symbol = '󰂁'
  style = 'dimmed green'

  [[battery.display]] # < 100%
  threshold = 99
  discharging_symbol = '󱈏'
  style = 'fg:#C37093'

# [palettes]

[palettes.foo]
# blue = '21'  # will overwrite
mustard = '#af8700'
bright_pink = 'bg:#D1005B fg:#23000F'
pink_bright_text = 'bg:#68032F fg:#F7BCD6'
pink_faded_text = 'bg:#68032F fg:#D7748C'
dark_pink = 'bg:#43001D fg:#C37093'
dark_pink_highlight = 'bg:#43001D fg:#D1005B'
