
# GOOD:
# theme = "onedark"             # Awesome
# theme = "monokai-extended"    # SAME AS BATCAT, THE BEST THEME FOR /etc/fstab
theme = "kaolin-valley-dark"  # EVALUATING
# theme = "starlight"         # better diff contrast than carbon 
# theme = "carbon"
# theme = "catppuccin_mocha"
# theme = "monokai_soda"
# theme = "tokyonight"
# theme = "kanagawa"
# AVOID:
# theme = "dracula_at_night" # bad yaml
# theme = "github_dark"      # bad yaml
# theme = "everblush"		     # bad diff

[editor]
true-color = true
line-number = "relative"
# mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.file-picker]
hidden = false
