[[language]]
name = "caddyfile"
file-types = [ "caddy", "Caddyfile" ]

[[language]]
name = "env"
file-types = [ "env", { glob = "env" } ]

[[language]]
name = "sshclientconfig"
file-types = [ { glob = "sshd*" }, {glob = "config"} ]

[[language]]
name = "markdown"
file-types = [ "md", "txt", "prompt" ]
