#!/bin/bash

PS="\[\e[5;92m\]\$(date +'%H:%M')\[\e[0m\] \[\033[01;34m\]\w\[\033[00m\] $\[\e[0m\]"

# Function to check if the current branch is ahead of the remote branch
function __prompt_command() {
    # This needs to be first
    local EXIT="$?"

    # Definitions
    local default_color="\[\e[0m\]"  # Reset color
    local warning_color="\[\e[33m\]" # Yellow color
    local error_color="\[\e[31m\]"   # Red color
    local default_symbol=''          # 
    local up_to_date_symbol="\[♡\]"      #
    local not_added_symbol="\[🔶\]"      # Symbol for case 
    local not_committed_symbol="\[🔷\]"  # Symbol for case 
    local ahead_symbol="\[🔺\]"          # Symbol for case 
    local behind_symbol="\[🔻\]"         # Symbol for case 

    # Default values
    local SYMBOL=""
    local COLOR="\[\e[0m\]"
    PS1=""

    # Check git status
    local git_status=$(git status 2>&1)
    
    if [[ $git_status == *"not a git repository"* ]]; then
        SYMBOL=$default_symbol
        COLOR=$default_color
    elif [[ $git_status == *"Untracked files:"* ]]; then
        SYMBOL=$not_added_symbol
        COLOR=$warning_color
    elif [[ $git_status == *"Changes not staged for commit"* ]]; then
        SYMBOL=$not_added_symbol
        COLOR=$warning_color
    elif [[ $git_status == *"Changes to be committed"* ]]; then
        SYMBOL=$not_committed_symbol
        COLOR=$warning_color
    elif [[ $git_status == *"Your branch is ahead"* ]]; then
        SYMBOL=$ahead_symbol
        COLOR=$warning_color
    elif [[ $git_status == *"Your branch is behind"* ]]; then
        SYMBOL=$behind_symbol
        COLOR=$warning_color
    elif [[ $git_status == *"Your branch is up to date"* ]]; then
        SYMBOL=$up_to_date_symbol
        COLOR=$default_color
    fi

    # Notify error, ovverrides warning
    if [ $EXIT != 0 ]; then
        COLOR=$error_color
    fi

    # echo -e "\e[90mDB: $database:$table\e[90m"
    PS1="${SYMBOL} \[\e[5;92m\]\$(date +'%H:%M')\[\e[0m\] \[\033[01;34m\]\w\[\033[00m\] ${COLOR}$\[\e[0m\]"

    # single integral ∫
    # Check if git status output is not empty
    white="\e[0;37m"
    _0="\e[0m"
    if [[ -n $(git status -s 2>/dev/null) ]]; then
        echo -e "${white}⌠ Δ$_0"
        # Store the total number of lines in the output
        total_lines=$(git -c color.status=always status -s | wc -l)
        # Iterate over each line of the output
        line_count=0
        while IFS= read -r line; do
            # Increment line count
            ((line_count++))
            # Prepend a character to the beginning of each line
            if ((line_count < total_lines)); then
                printf "${white}|$_0$line\n"
            else
                printf "${white}⌡$_0$line\n"
            fi
        done <<< "$(git -c color.status=always status -s)"
    fi
}

__prompt_command
