#!/bin/bash

# parent = bashrc

move-to-trash() {
    # Check if the TRASH environment variable is set
    if [[ -z "$TRASH" ]]; then
        echo 'Error: Please define the $TRASH environment variable.'
        return 1
    fi

    # Check if the TRASH directory exists
    if [[ ! -d "$TRASH" ]]; then
        echo "Error: The directory '$TRASH' does not exist."
        return 2
    fi

    # Move files to the TRASH directory
    if [[ $# -eq 0 ]]; then
        echo "Error: No files specified for deleting."
        return 3
    fi

    # Move files and check if the move was successful
    if mv -v "$@" "$TRASH" 2>/dev/null; then
        return $?
    else
        echo "Error: Failed to move files to $TRASH."
        return 4
    fi
}


# for antonmedv/walk
lk() {
  cd "$(walk "$@")"
}

errtest() { ls /non/existant/path; }
