#!/bin/bash

# NON-INTERACTIVE GUARD
[[ $- != *i* ]] && return

DEBUG_BASHRC=1

source "$HOME/.bash/dsl/00-loader.sh"

import? ~/.cargo/env
import? ~/.nvm/nvm.sh  # This loads nvm 

# modules
import ~/.env
import 01-aliases
import 02-shell
import 03-lesspipe
import 04-dircolors
import 05-completion
import 06-prompt
import 07-yazi

activate dns shell-completion bash
activate zoxide init bash

# MUST BE LAST
import 99-ble
